#!/usr/bin/env bash
# From-scratch setup wizard for the whole repo. Gathers the project name,
# database, and basic settings (prompting in a terminal, or reading them from
# env vars when run non-interactively, e.g. by the /bootstrap command), writes
# `.env`, then sets up JS deps, Rust, Postgres, migrations, and a backend build.
#
# Non-interactive use: pass any of PROJECT_NAME, DB_NAME, DB_USER, DB_PASSWORD,
# DB_PORT, OWNER_EMAIL, OWNER_PASSWORD, ORG_NAME, ORG_DOMAIN as env vars. Set
# FORCE_CONFIG=1 to rewrite an existing .env without asking.
set -euo pipefail

ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
cd "$ROOT"

step() { printf "\n\033[1;33m▶ %s\033[0m\n" "$1"; }
ok()   { printf "  \033[0;32m✓ %s\033[0m\n" "$1"; }
warn() { printf "  \033[0;31m! %s\033[0m\n" "$1"; }

slug_pkg() { echo "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/-/g; s/^-+|-+$//g'; }
slug_db()  { echo "$1" | tr '[:upper:]' '[:lower:]' | sed -E 's/[^a-z0-9]+/_/g; s/^_+|_+$//g'; }

# ask VAR "Prompt" "default" — keep an env-provided value, else prompt on a TTY,
# else fall back to the default.
ask() {
  local var="$1" prompt="$2" default="$3" reply
  if [[ -n "${!var:-}" ]]; then ok "$prompt: ${!var}"; return; fi
  if [[ -t 0 ]]; then
    read -rp "  $prompt [$default]: " reply
    printf -v "$var" '%s' "${reply:-$default}"
  else
    printf -v "$var" '%s' "$default"
    ok "$prompt: $default (default)"
  fi
}

have() { command -v "$1" >/dev/null 2>&1; }

# ── 0. Prerequisites ─────────────────────────────────────────
step "Checking prerequisites"
have node   || { warn "node not found — install Node 20+"; exit 1; }
have cargo  || { warn "cargo not found — install Rust (https://rustup.rs)"; exit 1; }
have docker || { warn "docker not found — install Docker Desktop"; exit 1; }
ok "node $(node --version), cargo $(cargo --version | awk '{print $2}'), docker present"

# ── 1. Configure (project name, database, basics) ────────────
NEED_CONFIG=1
if [[ -f .env && "${FORCE_CONFIG:-0}" != "1" ]]; then
  if [[ -t 0 ]]; then
    read -rp $'\n  .env already exists — reconfigure from scratch? (y/N): ' ans
    [[ "${ans,,}" == y* ]] || NEED_CONFIG=0
  else
    NEED_CONFIG=0
  fi
fi

if [[ "$NEED_CONFIG" == "1" ]]; then
  step "Project setup — answer or accept the suggested defaults"
  ask PROJECT_NAME  "Project name"          "Core Admin"
  ask DB_NAME       "Postgres database"     "$(slug_db "$PROJECT_NAME")"
  ask DB_USER       "Postgres user"         "$(slug_db "$PROJECT_NAME")"
  ask DB_PASSWORD   "Postgres password"     "devpassword"
  ask DB_PORT       "Postgres host port"    "5440"
  ask ORG_DOMAIN    "Organization domain"   "example.com"
  ask ORG_NAME      "Organization name"     "$PROJECT_NAME"
  ask OWNER_EMAIL   "Seed owner email"      "owner@${ORG_DOMAIN}"
  ask OWNER_PASSWORD "Seed owner password"  "changeme-dev-only"

  PKG_NAME="$(slug_pkg "$PROJECT_NAME")"
  DATABASE_URL="postgres://${DB_USER}:${DB_PASSWORD}@localhost:${DB_PORT}/${DB_NAME}?sslmode=disable"

  step "Writing .env"
  [[ -f .env ]] && cp .env .env.bak && warn "backed up existing .env → .env.bak"
  cat > .env <<EOF
# Generated by scripts/bootstrap.sh for "${PROJECT_NAME}".

# ── Database ────────────────────────────────────────────────
POSTGRES_USER=${DB_USER}
POSTGRES_PASSWORD=${DB_PASSWORD}
POSTGRES_DB=${DB_NAME}
PG_HOST_PORT=${DB_PORT}
DATABASE_URL=${DATABASE_URL}

# ── API server ──────────────────────────────────────────────
API_BIND_ADDR=127.0.0.1:8080
WEB_ORIGIN=http://localhost:5173
SESSION_TTL_SECS=604800
COOKIE_SECURE=false

# ── First-boot seed (idempotent: only runs when no users exist) ──
SEED_OWNER=true
SEED_OWNER_EMAIL=${OWNER_EMAIL}
SEED_OWNER_PASSWORD=${OWNER_PASSWORD}
SEED_ORG_NAME="${ORG_NAME}"
SEED_ORG_DOMAIN=${ORG_DOMAIN}

# ── Frontend ────────────────────────────────────────────────
VITE_API_BASE=http://localhost:8080
EOF
  ok "wrote .env"

  # Rename the monorepo package to match the project.
  node -e "const fs=require('fs');const p=JSON.parse(fs.readFileSync('package.json'));p.name='${PKG_NAME}';fs.writeFileSync('package.json',JSON.stringify(p,null,2)+'\n')"
  ok "set root package name → ${PKG_NAME}"

  if [[ -f .env.bak ]]; then
    warn "database settings changed — if a Postgres volume already exists, run 'pnpm db:reset' to recreate it with the new name/credentials"
  fi
else
  ok "keeping existing .env"
fi

# DATABASE_URL for the steps below (read from whatever .env we have now).
export DATABASE_URL="$(grep -E '^DATABASE_URL=' .env | head -1 | cut -d= -f2-)"

# ── 2. pnpm + JS deps ────────────────────────────────────────
step "Package manager (pnpm)"
have pnpm || { warn "pnpm not found — installing globally via npm"; npm install -g pnpm; }
ok "pnpm $(pnpm --version)"

step "Installing JS dependencies"
pnpm install
ok "workspace dependencies installed"

# ── 3. Rust toolchain (pinned in apps/api/rust-toolchain.toml) ─
step "Rust toolchain"
( cd apps/api && cargo --version >/dev/null )
ok "toolchain ready ($(cd apps/api && rustc --version | awk '{print $2}'))"

# ── 4. Postgres ──────────────────────────────────────────────
step "Starting Postgres"
bash scripts/db-up.sh
ok "Postgres up and healthy"

# ── 5. Migrations ────────────────────────────────────────────
step "Running migrations"
if have sqlx; then
  ( cd apps/api && sqlx migrate run --source migrations )
  ok "migrations applied via sqlx-cli"
else
  warn "sqlx-cli not installed — the API runs migrations itself on first boot"
fi

# ── 6. Build the backend ─────────────────────────────────────
step "Building the backend"
( cd apps/api && cargo build )
ok "backend compiled"

# ── 7. Done ──────────────────────────────────────────────────
step "Bootstrap complete"
cat <<EOF
  Start everything:    pnpm dev
  Frontend:            http://localhost:5173
  API:                 http://localhost:8080
  Sign in as the seeded Owner (created on first API boot):
    $(grep -E '^SEED_OWNER_EMAIL=' .env | cut -d= -f2-) / $(grep -E '^SEED_OWNER_PASSWORD=' .env | cut -d= -f2-)

  Other commands:      pnpm test · pnpm lint · pnpm e2e · pnpm db:reset
EOF
